language: python
python:
  - "3.6"
cache: pip

install:
  - pip install poetry

script:
  - poetry install -vvv
  - hush_keygen --name test
  - poetry run jsctl config update private_key_path "`pwd`/test.priv"
  - poetry run pytest tests/ -s --cov=jumpscale

after_success:
  - poetry run codecov
