name: Build docker image

on:
  push:
    tags:
      - '**'
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: olegtarasov/get-tag@v2 # getting tagname
          id: tagName
        - uses: docker/build-push-action@v1
          with:
            repository: threefoldtech/js-ng
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            dockerfile: jumpscale/install/Dockerfile
            tags: ${{ steps.tagName.outputs.tag }}