name: Build docker image

on:
  push:
    branches: [ development ]
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        # - uses: mr-smithers-excellent/docker-build-push@v3
        - uses: docker/build-push-action@v1
          with:
            repository: threefoldtech/js-ng
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            dockerfile: jumpscale/install/Dockerfile
            tags: latest
        - name: upload to flist
          run: |
            docker save threefoldtech/js-ng:latest | gzip > js-ng-latest.tar.gz
            curl -v -X POST  -H 'Authorization: bearer ${{ secrets.ZEROHUB_TOKEN}}' ${{secrets.ZEROHUB_URL}}/api/flist/me/upload -F 'file=@js-ng-latest.tar.gz'
