name: Build docker image

on:
  push:
    tags:
      - '**'
jobs:
    build-tagged-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: olegtarasov/get-tag@v2 # getting tagname
          id: tagName
        - uses: docker/build-push-action@v1
          with:
            repository: threefoldtech/js-ng
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            dockerfile: jumpscale/install/Dockerfile
            tags: ${{ steps.tagName.outputs.tag }}
        - name: upload to flist
          run: |
            sudo apt-get update && sudo apt-get install curl -y
            docker save threefoldtech/js-ng:${{ steps.tagName.outputs.tag }} docker save threefoldtech/js-ng:latest | gzip > js-ng-${{ steps.tagName.outputs.tag }}.tar
            curl -X POST  -H 'Authorization: bearer ${{secrets.ZEROHUB_TOKEN}}' ${{secrets.ZEROHUB_URL}}/api/flist/me/upload -F 'file=@js-ng-${{ steps.tagName.outputs.tag }}.tar'
